### ISSUE TITLE
Main.GetDirectorySize: Out of bounds.

### ISSUE THREAD

**Issue by eigengrau** [sebikul/mundus#1]
When starting Mundus 3.0.0, execution exits right away and returns status code 1. The following is reported:

```
Main.GetDirectorySize.97: #21: Out of bounds
_TreeView._SetItemSelected.1136 _TreeView.Sort_Timer.1286 
```

**Comment by sebikul** [comment]
Thanks for the report! That error seems weird because that line of code does not touch the interface at all. I will look into it, but if it requires a significant amount of time I won't be issuing a fix as I'm in the process of rewriting Mundus to another language.

**Comment by Brt-L** [comment]
Found the bug in the code.

Check [.src/Main.module, Function GetDirectorySize](http://bazaar.launchpad.net/~sebikul/mundus/trunk/view/head:/.src/Main.module#L117)
    line 123 reads:            Shell "du -bs " & Shell(Path) To sSize
    Needs a change to:     Shell "du -bs " & Path To sSize

Now Mundus can get working again ...

B.

**Comment by sebikul** [comment]
Thanks for the patch @Ba-l-am, but that leaves Mundus vulnerable to shell injections, as the path is not sanitized. The bug is in the way the Shell function parses the ~ character, which should resolve to /home/$USER. I will push a fix shortly.
Thanks again for the help!

**Comment by sebikul** [comment]
The bug should be fixed in commit bc907761723b955cad8a13c3c3cafd4cfe78dcb7. Can you confirm? I will push an update shortly.

**Comment by Brt-L** [comment]
downloaded source and did make install
Mundus is starting up and doing well ...

(Xubuntu 14.04.03)

Tnx.

**Comment by sebikul** [comment]
Great! The new version is live!

Thanks a lot for your help!

**Comment by eigengrau** [comment]
Thanks!
