### ISSUE TITLE
question: requeriments

### ISSUE THREAD

**Issue by mckaygerhard** [sebikul/mundus#7]
i can see some modules, i assume that this proyect can be use also in gambas 3.1 (where JSON are not still available, as i can see it implemented in your code at laeas way to manipulate it)

if there's possitive, whitc modules do you implemented already? can give me more descriptive about it? i already have making a gambas mini framework utility and have interesit in some par of your code!

**Comment by sebikul** [comment]
Yes, I included the JSON class as a module for those cases. You can find the supported modules in the ./modules folder

**Comment by mckaygerhard** [comment]
umm ok very resumed the response, but well in any way i m obey to see and analize the code.. thanks.. good proyect
